const PERMISSIONS = {
  MANAGE_NEWS: 'manage_news',
  MANAGE_VACANCIES: 'manage_vacancies',
  VIEW_USERS: 'view_users',
  VIEW_TEAMS: 'view_teams',
  DELETE_USERS: 'delete_users',
  DELETE_TEAMS: 'delete_teams',
  REVIEW_TEAM_REQUESTS: 'review_team_requests',
  VIEW_AUDIT_LOGS: 'view_audit_logs',

  REQUEST_TEAM_CREATION: 'request_team_creation',
  VIEW_OWN_TEAM_REQUESTS: 'view_own_team_requests',
  VIEW_TEAM_DETAILS: 'view_team_details',
  VIEW_AVAILABLE_PARTICIPANTS: 'view_available_participants',
  ASSIGN_CO_LEADER: 'assign_co_leader',
  REMOVE_PARTICIPANT: 'remove_participant',
  REVIEW_JOIN_REQUESTS: 'review_join_requests',
  VIEW_TEAM_AUDIT_LOGS: 'view_team_audit_logs',

  VIEW_OPEN_TEAMS: 'view_open_teams',
  REQUEST_JOIN_TEAM: 'request_join_team',
  VIEW_OWN_JOIN_REQUESTS: 'view_own_join_requests',

  CREATE_PROJECT: 'create_project',
  ASSIGN_PROJECT: 'assign_project',
  VIEW_TEAM_PROJECTS: 'view_team_projects',
  VIEW_TEAM_ANALYTICS: 'view_team_analytics',
  VIEW_TEAM_ACTIVITY_LOGS: 'view_team_activity_logs',
  VIEW_ASSIGNED_PROJECTS: 'view_assigned_projects',
  UPDATE_ASSIGNED_PROJECT_STATUS: 'update_assigned_project_status',
  VIEW_PROJECT_FILES: 'view_project_files',
  UPLOAD_PROJECT_FILES: 'upload_project_files',
  VIEW_TEAM_CHAT: 'view_team_chat',
  SEND_TEAM_CHAT: 'send_team_chat',

  VIEW_NOTIFICATIONS: 'view_notifications',
  MANAGE_NOTIFICATIONS: 'manage_notifications'
};

const ROLE_PERMISSIONS = {
  admin: [
    PERMISSIONS.MANAGE_NEWS,
    PERMISSIONS.MANAGE_VACANCIES,
    PERMISSIONS.VIEW_USERS,
    PERMISSIONS.VIEW_TEAMS,
    PERMISSIONS.DELETE_USERS,
    PERMISSIONS.DELETE_TEAMS,
    PERMISSIONS.REVIEW_TEAM_REQUESTS,
    PERMISSIONS.VIEW_AUDIT_LOGS,
    PERMISSIONS.VIEW_NOTIFICATIONS,
    PERMISSIONS.MANAGE_NOTIFICATIONS
  ],
  leader: [
    PERMISSIONS.REQUEST_TEAM_CREATION,
    PERMISSIONS.VIEW_OWN_TEAM_REQUESTS,
    PERMISSIONS.VIEW_TEAM_DETAILS,
    PERMISSIONS.VIEW_AVAILABLE_PARTICIPANTS,
    PERMISSIONS.ASSIGN_CO_LEADER,
    PERMISSIONS.REMOVE_PARTICIPANT,
    PERMISSIONS.REVIEW_JOIN_REQUESTS,
    PERMISSIONS.VIEW_TEAM_AUDIT_LOGS,
    PERMISSIONS.CREATE_PROJECT,
    PERMISSIONS.ASSIGN_PROJECT,
    PERMISSIONS.VIEW_TEAM_PROJECTS,
    PERMISSIONS.VIEW_TEAM_ANALYTICS,
    PERMISSIONS.VIEW_TEAM_ACTIVITY_LOGS,
    PERMISSIONS.VIEW_PROJECT_FILES,
    PERMISSIONS.UPLOAD_PROJECT_FILES,
    PERMISSIONS.VIEW_TEAM_CHAT,
    PERMISSIONS.SEND_TEAM_CHAT,
    PERMISSIONS.VIEW_NOTIFICATIONS,
    PERMISSIONS.MANAGE_NOTIFICATIONS
  ],
  'co-leader': [
    PERMISSIONS.VIEW_TEAM_DETAILS,
    PERMISSIONS.VIEW_TEAM_PROJECTS,
    PERMISSIONS.VIEW_TEAM_ANALYTICS,
    PERMISSIONS.VIEW_TEAM_AUDIT_LOGS,
    PERMISSIONS.VIEW_PROJECT_FILES,
    PERMISSIONS.UPLOAD_PROJECT_FILES,
    PERMISSIONS.VIEW_NOTIFICATIONS,
    PERMISSIONS.MANAGE_NOTIFICATIONS
  ],
  participant: [
    PERMISSIONS.VIEW_TEAM_DETAILS,
    PERMISSIONS.VIEW_OPEN_TEAMS,
    PERMISSIONS.REQUEST_JOIN_TEAM,
    PERMISSIONS.VIEW_OWN_JOIN_REQUESTS,
    PERMISSIONS.VIEW_ASSIGNED_PROJECTS,
    PERMISSIONS.UPDATE_ASSIGNED_PROJECT_STATUS,
    PERMISSIONS.VIEW_PROJECT_FILES,
    PERMISSIONS.UPLOAD_PROJECT_FILES,
    PERMISSIONS.VIEW_TEAM_CHAT,
    PERMISSIONS.SEND_TEAM_CHAT,
    PERMISSIONS.VIEW_NOTIFICATIONS,
    PERMISSIONS.MANAGE_NOTIFICATIONS
  ]
};

function getPermissionsForRole(role) {
  return ROLE_PERMISSIONS[role] || [];
}

function hasPermission(role, permission) {
  return getPermissionsForRole(role).includes(permission);
}

module.exports = {
  PERMISSIONS,
  ROLE_PERMISSIONS,
  getPermissionsForRole,
  hasPermission
};
